name: Generate STL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.11

    - name: Build STL with Nix
      run: nix build .#stl

    - name: Upload STL artifact
      uses: actions/upload-artifact@v4
      with:
        name: mini-puck-stl
        path: result/mini_puck.stl